initializr:
  group-id:
    title: adesso group
    description: The group id of the project
    value: com.adesso
  dependencies:
    - name: Web
      content:
        - name: Web
          id: web
    - name: Utilities
      content:
        - name: Mapstruct
          id: mapstruct
          groupId: org.mapstruct
          artifactId: mapstruct
          version: "1.5.3.Final"
          description: Mapstruct object mapper library
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
  bootVersions:
    - id: 3.2.3
      name: 3.2.3
      default: false
    - id: 2.3.12.RELEASE
      name: 2.3.12 (RELEASE)
      default: false
    - id: 3.3.1
      name: 2.3.2
      default: true
  javaVersions:
    - id: 22
      name: 22
      default: true
    - id: 21
      name: 21
      default: false
    - id: 11
      name: 11
      default: false
    - id: 17
      name: 17
      default: false
  packagings:
    - name: Jar
      id: jar
      default: true
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip