initializr:
  group-id:
    title: adesso group
    description: The group id of the project
    value: com.adesso
  dependencies:
    - name: Web
      content:
        - name: Web
          id: web
    - name: Utilities
      content:
        - name: Mapstruct
          id: mapstruct
          groupId: org.mapstruct
          artifactId: mapstruct
          version: "1.5.3.Final"
          description: Mapstruct object mapper library
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
  javaVersions:
    - id: 22
      name: newest Java version
      default: true
  packagings:
    - name: Jar
      id: jar
      default: true
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip